# Generated by Django 4.1.7 on 2023-02-26 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=256)),
                ('phone_number', models.CharField(max_length=20)),
                ('customer_id', models.CharField(max_length=256)),
                ('order_id', models.CharField(max_length=256)),
                ('cf_order_id', models.CharField(max_length=2500)),
                ('payment_session_id', models.CharField(max_length=3000)),
                ('amount', models.IntegerField()),
                ('is_paid', models.BooleanField(default=False)),
            ],
        ),
    ]
