version: '3'

services:
  api:
    image: kando/Rehmat
    build:
      context: .
      dockerfile: ./Dockerfile
    ports: 
      - "7376:7376"
    volumes:
      - ./static/:/app/static/
      - ./logs/:/app/logs/
      - ./media/:/app/media/
      - ./database/:/app/database/
