# Generated by Django 4.1.7 on 2023-02-25 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=256, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('phone_no', models.CharField(max_length=20, unique=True)),
                ('dob', models.DateField()),
                ('city', models.CharField(max_length=128)),
                ('country', models.CharField(max_length=128)),
                ('id_proof', models.ImageField(upload_to='')),
                ('role', models.CharField(choices=[['RF', 'Refugee'], ['DR', 'Doctor']], max_length=2)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
