# Generated by Django 4.1.7 on 2023-02-25 09:37

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='dob',
            new_name='date_of_birth',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='phone_no',
            new_name='phone_number',
        ),
        migrations.AlterField(
            model_name='user',
            name='id_proof',
            field=models.ImageField(upload_to=user.models.id_upload_to),
        ),
    ]
