# Generated by Django 4.1.7 on 2023-02-26 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slot', '0003_scheduledslot_uid_alter_scheduledslot_channel_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scheduledslot',
            old_name='token',
            new_name='token1',
        ),
        migrations.RenameField(
            model_name='scheduledslot',
            old_name='uid',
            new_name='uid1',
        ),
        migrations.AddField(
            model_name='scheduledslot',
            name='token2',
            field=models.CharField(blank=True, default='', max_length=2500),
        ),
        migrations.AddField(
            model_name='scheduledslot',
            name='uid2',
            field=models.CharField(blank=True, default='', max_length=1500),
        ),
    ]
