# Generated by Django 4.1.7 on 2023-02-26 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_is_verified_doctor'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValidationImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.CharField(max_length=2500)),
            ],
        ),
    ]
