# Generated by Django 4.1.7 on 2023-02-26 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_user_gender_user_unhrc_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='gender',
        ),
    ]
